language: python
python:
  - "2.7"
services:
  - memcached
before_install:
  - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.90.13.deb && sudo dpkg -i elasticsearch-0.90.13.deb
  - sudo /usr/share/elasticsearch/bin/plugin -install elasticsearch/elasticsearch-analysis-icu/1.13.0
  - sudo /usr/share/elasticsearch/bin/elasticsearch -Des.config=scripts/elasticsearch/elasticsearch.yml
install:
  - make update_deps
  - pip install --no-deps -r requirements/test.txt --find-links https://pyrepo.addons.mozilla.org/
  - pip install --no-deps -r requirements/compiled.txt --find-links https://pyrepo.addons.mozilla.org/
  - npm install
before_script:
  - mysql -e 'create database olympia;'
  - make update_assets
script:
  - DJANGO_SETTINGS_MODULE=settings_ci make test
notifications:
  irc:
    channels:
      - "irc.mozilla.org#amo-bots"
    on_success: change
    on_failure: always
