language: python
python:
  - "2.6"
  - "2.7"
services:
  - memcached
before_install:
  - sudo apt-get install swig
  - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.3.2.deb && sudo dpkg -i elasticsearch-1.3.2.deb
  - sudo /usr/share/elasticsearch/bin/elasticsearch -d -D es.path.data=/tmp -D es.gateway.type=none -D es.index.store.type=memory -D es.discovery.zen.ping.multicast.enabled=false
install:
  - make update_deps
  - npm install
before_script:
  - mysql -e 'create database olympia;'
  - make update_assets
script:
  - DJANGO_SETTINGS_MODULE=settings_ci make flake8 && DJANGO_SETTINGS_MODULE=settings_ci make test
  - make docs SPHINXOPTS='-nW'
notifications:
  irc:
    channels:
      - "irc.mozilla.org#amo-bots"
    on_success: change
    on_failure: always
