language: python
sudo: false

python:
  - 2.7

env:
  global:
    - secure: "bYe6WOTAnlS8Ru4ODWSSOnHffxcN23NkKZh4M0eO510HvZGCMB4zZn8afiVKGXd1YqsoRfMXTBZJ0yBcFEvWnyH7S4kd+7d1PpNS4kgLVKtLCW5d7Wc5GA6uh1jWLS+zKFBNN5sZ8OVc7rCsLCBRDEoI94wBKYwDX2Kk1WKylz8="
    - AUTOGRAPH_SERVER_URL: http://localhost:5500
    - PYTHONPATH: src
    - ADDONS_LINTER_BIN: $TRAVIS_BUILD_DIR/node_modules/.bin/addons-linter
    - DJANGO_SETTINGS_MODULE: settings_test
    - RUNNING_IN_CI: True

aliases:
  - &run-pytest
    if: type IN (pull_request, push)
    stage: main tests
    script: |
      make -f Makefile-docker update_deps
      pytest -n 2 -m 'not (es_tests or needs_locales_compilation or signing)' --test-group-count=8 --test-group=$PYTEST_TEST_GROUP src/


jobs:
  include:
    - stage: main tests
      env: TEST=flake8
      script: |
        pip install -r requirements/flake8.txt
        make flake8
    - stage: main tests
      env: TEST=docs
      script: |
        pip install -r requirements/docs.txt
        make -f Makefile-docker docs SPHINXOPTS='-nW'
    - stage: main tests
      env: TEST=assets
      script: |
        make -f Makefile-docker update_deps
        make -f Makefile-docker update_assets
    - stage: main tests
      env: TEST=elasticsearch
      if: type IN (pull_request, push)
      script: |
        make -f Makefile-docker update_deps
        pytest -n 2 -m "es_tests and not needs_locales_compilation" src/
    - <<: *run-pytest
      env: PYTEST_TEST_GROUP=1
    - <<: *run-pytest
      env: PYTEST_TEST_GROUP=2
    - <<: *run-pytest
      env: PYTEST_TEST_GROUP=3
    - <<: *run-pytest
      env: PYTEST_TEST_GROUP=4
    - <<: *run-pytest
      env: PYTEST_TEST_GROUP=5
    - <<: *run-pytest
      env: PYTEST_TEST_GROUP=6
    - <<: *run-pytest
      env: PYTEST_TEST_GROUP=7
    - <<: *run-pytest
      env: PYTEST_TEST_GROUP=8

  # # - <<: *test-signing
  # #   script: ./scripts/start-autograph.sh
  # # - name: locale-dependend-tests
  # #   -m 'needs_locales_compilation'
  # - name: extract-locales
  #   if: type = cron AND branch = master
  #   script: bash scripts/travis-extract-l10n.sh

cache:
  pip: true
  directories:
    - node_modules
    - $HOME/.gimme

services:
  - mysql
  - memcached
  - elasticsearch
  - redis

addons:
  apt:
    sources:
      - elasticsearch-5.x
    packages:
      - swig
      - oracle-java8-set-default
      - elasticsearch
      - gettext
      - librsvg2-bin
      - pngcrush

before_install:
  - mysql -e 'create database olympia;'
  - export GOPATH=$HOME/go
  - export PATH=$HOME/usr/local/go/bin:$GOPATH/bin:$PATH

install:
  - nvm current
  - nvm deactivate
  - nvm install 6
  - nvm use 6
  - pip install --upgrade pip wheel setuptools pytest-test-groups

before_script:
  - mysql --version
  - node --version
  - java -version
  - curl -v http://localhost:9200/

notifications:
  irc:
    channels:
      - "irc.mozilla.org#amo-bots"
    on_success: change
    on_failure: always

git:
  depth: 1
